# Generated by Django 6.0.4 on 2026-06-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
    ]
